### ISSUE TITLE
💀

### ISSUE THREAD

**Issue by shibby360** [Aneeshy720/Website#1]
https://github.com/Aneeshy720/Website/blob/3e60a452ff1603ba560a752ef69d1d52f921838e/home.py#L14

aint no way bro actually plays fortnite

**Comment by Aneeshy720** [comment]
dude i had to make up some random shit for python class. i did in like 2
mins

**Comment by shibby360** [comment]
goddamn that was fast lmao
also can you add me as a collaborator
